services:
  jinja2-cli:
    image: ireshmm/jinja2-cli:0.0.4
    build: .
    volumes:
      - ./test/input.yaml:/home/app/input:ro
      - ./test/template.j2:/home/app/template.j2:ro
      - ./test/output.txt:/home/app/output
    stop_grace_period: 0s
    develop:
      watch:
        - path: ./entrypoint.sh
          action: sync+restart
          target: /home/app/entrypoint.sh
        - path: ./
          ignore:
           - ./test/output.txt
           - .git/
          action: sync+restart
          target: /tmp/a
  keepalive:
    image: busybox:latest
    command: sleep infinity
    stop_grace_period: 0s